### ISSUE TITLE
Ugly font

### ISSUE THREAD

**Issue by JasonHK** [Saren-Arterius/simple-blog#2]
Can you add the support of [Source Han Sans](https://zh.wikipedia.org/wiki/%E6%80%9D%E6%BA%90%E9%BB%91%E9%AB%94), Microsoft JhengHei, Heiti TC and Helvetica?

**Comment by Saren-Arterius** [comment]
我諗係電腦字體設定問題掛，我依家用起上黎幾靚
![a](http://drop.wtako.net/file/08450f94fd79e76b3f54a4ae91968e4673c6f7d9.png)

**Comment by JasonHK** [comment]
It is better now!
![](http://i.imgur.com/vd94OJ0.png)
